In [1]:
# import libraries
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import MissingIndicator,SimpleImputer

In [2]:
# load datasets
df = pd.read_csv('data/titanic_temp.csv',usecols=['Age','Fare','Survived'])
df.head()

Age     Fare  Survived
0  22.0   7.2500         0
1  38.0  71.2833         1
2  26.0   7.9250         1
3  35.0  53.1000         1
4  35.0   8.0500         0

In [14]:
df.isnull().mean()*100

Age         20.212766
Fare         0.000000
Survived     0.000000
dtype: float64

In [15]:
df = df.dropna(subset=['Fare'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 846 entries, 0 to 890
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       675 non-null    float64
 1   Fare      846 non-null    float64
 2   Survived  846 non-null    int64  
dtypes: float64(2), int64(1)
memory usage: 26.4 KB


In [16]:
#split data into train test
X = df.drop(columns=['Survived'])
y = df['Survived']

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)
X_train.head()

Age      Fare
603  44.0    8.0500
550  17.0  110.8833
344  36.0   13.0000
654  18.0    6.7500
132  47.0   14.5000

In [18]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)

X_test_trf = si.transform(X_test)
X_train_trf

array([[ 44.        ,   8.05      ],
       [ 17.        , 110.8833    ],
       [ 36.        ,  13.        ],
       ...,
       [ 29.50031776,   7.2292    ],
       [ 39.        ,  79.65      ],
       [ 21.        ,   7.925     ]])

### without is_missing column

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

clf = LogisticRegression()

clf.fit(X_train_trf,y_train)

y_pred = clf.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.6705882352941176

### with is_missing column

In [20]:
mi = MissingIndicator()

mi.fit(X_train)

MissingIndicator()

In [21]:
mi.features_

array([0], dtype=int64)

In [22]:
train_is_missing = mi.transform(X_train)
train_is_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [

In [23]:
test_is_missing = mi.transform(X_test)
test_is_missing

array([[False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [

In [25]:
X_train['is_missing_age'] = train_is_missing
X_train.head()

Age      Fare  is_missing_age
603  44.0    8.0500           False
550  17.0  110.8833           False
344  36.0   13.0000           False
654  18.0    6.7500           False
132  47.0   14.5000           False

In [26]:
X_test['is_missing_age'] = test_is_missing
X_test.head()

Age      Fare  is_missing_age
234  24.0   10.5000           False
424  18.0   20.2125           False
358   NaN    7.8792            True
391  21.0    7.7958           False
268  58.0  153.4625           False

In [27]:
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [28]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf2,y_train)

y_pred = clf.predict(X_test_trf2)

In [29]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6705882352941176

### By using sklearn simple imputer

In [30]:
si = SimpleImputer(add_indicator=True)

X_train = si.fit_transform(X_train)
X_test = si.transform(X_test)

In [31]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf2,y_train)

y_pred = clf.predict(X_test_trf2)

In [32]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6705882352941176